/*
 * Comment by Kevin @ Kyaw Thiha
 * All the following code is generated by ChatGPT, but double checked by me.
 * These codes are not meant to be run.
 * Instead, they are meant to act as example API usage on how to consume the viewModels inside the views.
 *
 * Linked to /res/layout/activity_medicine_log_example.xml
 */

package com.example.b07project.view.child;

import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.lifecycle.ViewModelProvider;

import com.example.b07project.R;
import com.example.b07project.model.MedicineLog;
import com.example.b07project.viewModel.MedicineLogViewModel;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;

import java.util.HashMap;
import java.util.Map;

/**
 * Minimal example showing how to use MedicineLogViewModel.
 *
 * Demonstrates:
 * - getting the ViewModel
 * - observing getLog() / getLogError()
 * - calling loadLogByUser()
 * - calling addLog()
 * - example usage of updateInventory() and deleteInventory()
 */
public class MedicineLogExampleActivity extends AppCompatActivity {

  private static final boolean DEBUG_TOOLS_ENABLED = false;

  private MedicineLogViewModel viewModel;
  private TextView textStatus;
  private String uid;

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_medicine_log_example);

    textStatus = findViewById(R.id.textStatus);
    Button buttonAddExampleLog = findViewById(R.id.buttonAddExampleLog);
    Button buttonUpdateExampleLog = findViewById(R.id.buttonUpdateExampleLog);
    Button buttonDeleteExampleLog = findViewById(R.id.buttonDeleteExampleLog);

    FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
    if (user == null) {
      textStatus.setText(R.string.child_dashboard_no_user);
      return;
    }
    uid = user.getUid();

    // 1. Get ViewModel (pattern your friends should copy)
    viewModel = new ViewModelProvider(this).get(MedicineLogViewModel.class);
    setupObservers();

    viewModel.loadLogByUser(uid);

    if (DEBUG_TOOLS_ENABLED) {
      buttonUpdateExampleLog.setOnClickListener(v -> exampleUpdateLog());
      buttonDeleteExampleLog.setOnClickListener(v -> exampleDeleteLog());
      buttonAddExampleLog.setOnClickListener(v -> addExampleLog());
    } else {
      buttonAddExampleLog.setVisibility(View.GONE);
      buttonUpdateExampleLog.setVisibility(View.GONE);
      buttonDeleteExampleLog.setVisibility(View.GONE);
    }
  }

  private void setupObservers() {
    viewModel.getLog().observe(this, logs -> {
      int count = (logs == null) ? 0 : logs.size();
      updateStatus("Total logs: " + count);
    });

    viewModel.getLogError().observe(this, error -> {
      if (error != null && !error.isEmpty()) {
        updateStatus(error);
      }
    });
  }

  private void updateStatus(String text) {
    if (textStatus != null) {
      textStatus.setText(text);
    }
  }

  private void addExampleLog() {
    long now = System.currentTimeMillis();
    MedicineLog log = new MedicineLog(
        now,
        2,
        "250",
        "290",
        uid
    );
    viewModel.addLog(uid, log);
  }

  /**
   * Example: how to call updateInventory on the ViewModel.
   * Your teammate will usually call this from:
   * - a RecyclerView item click, where they already know the logId.
   */
  private void exampleUpdateLog() {
    // Replace with a real log key from Firebase
    String exampleLogId = "REPLACE_WITH_REAL_LOG_ID";

    Map<String, Object> updates = new HashMap<>();
    updates.put("doseCount", 3); // change dose count
    updates.put("breathRating", 5.0f); // change breath rating

    viewModel.updateInventory(uid, exampleLogId, updates);
    // ViewModel will call loadLogByUser(uid) again internally
  }

  /**
   * Example: how to call deleteInventory on the ViewModel.
   */
  private void exampleDeleteLog() {
    // Replace with a real log key from Firebase
    String exampleLogId = "REPLACE_WITH_REAL_LOG_ID";

    viewModel.deleteInventory(uid, exampleLogId);
    // Again, ViewModel will refresh the list
  }
}
