/*
 * Comment by Kevin @ Kyaw Thiha
 * All the following code is generated by ChatGPT, but double checked by me.
 * These codes are not meant to be run.
 * Instead, they are meant to act as example API usage on how to consume the viewModels inside the views.
 *
 * Linked to /res/layout/activity_medicine_log_example.xml
 */

package com.example.b07project.view.child;

import android.os.Bundle;
import android.widget.Button;
import android.widget.TextView;

import androidx.appcompat.app.AppCompatActivity;
import androidx.lifecycle.ViewModelProvider;

import com.example.b07project.R;
import com.example.b07project.model.MedicineLog;
import com.example.b07project.viewModel.MedicineLogViewModel;

import java.util.HashMap;
import java.util.Map;

/**
 * Minimal example showing how to use MedicineLogViewModel.
 *
 * Demonstrates:
 * - getting the ViewModel
 * - observing getLog() / getLogError()
 * - calling loadLogByUser()
 * - calling addLog()
 * - example usage of updateInventory() and deleteInventory()
 */
public class MedicineLogExampleActivity extends AppCompatActivity {

  private MedicineLogViewModel viewModel;
  private TextView textStatus;

  // In real app: FirebaseAuth.getInstance().getCurrentUser().getUid()
  private final String uid = "REPLACE_WITH_REAL_UID";

  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_medicine_log_example);

    textStatus = findViewById(R.id.textStatus);
    Button buttonAddExampleLog = findViewById(R.id.buttonAddExampleLog);
    Button buttonUpdateExampleLog = findViewById(R.id.buttonUpdateExampleLog);
    Button buttonDeleteExampleLog = findViewById(R.id.buttonDeleteExampleLog);

    // 1. Get ViewModel (pattern your friends should copy)
    viewModel = new ViewModelProvider(this).get(MedicineLogViewModel.class);

    // 2. Observe list of logs
    viewModel.getLog().observe(this, logs -> {
      int count = (logs == null) ? 0 : logs.size();
      textStatus.setText("Total logs: " + count);
    });

    // 3. Observe errors
    viewModel.getLogError().observe(this, error -> {
      if (error != null && !error.isEmpty()) {
        textStatus.setText(error);
      }
    });

    // 4. Initial load for this user
    viewModel.loadLogByUser(uid);

    // 5. Add an example log when button is clicked
    buttonAddExampleLog.setOnClickListener(v -> {
      long now = System.currentTimeMillis();
      MedicineLog log = new MedicineLog(
          now,
          2, // doseCount
          250f, // preCheck
          290f, // postCheck
          "good" // breathRating
      );

      viewModel.addLog(uid, log);
      // ViewModel reloads and LiveData updates the UI
    });

    // 6. Wire buttons to the example update/delete methods

    // When clicked, this will call updateInventory(...) with example data.
    buttonUpdateExampleLog.setOnClickListener(v -> exampleUpdateLog());

    // When clicked, this will call deleteInventory(...) with example data.
    buttonDeleteExampleLog.setOnClickListener(v -> exampleDeleteLog());

    // NOTE: exampleUpdateLog() and exampleDeleteLog() are just templates.
    // Replace the "REPLACE_WITH_REAL_LOG_ID" with a real key from Firebase.
  }

  /**
   * Example: how to call updateInventory on the ViewModel.
   * Your teammate will usually call this from:
   * - a RecyclerView item click, where they already know the logId.
   */
  private void exampleUpdateLog() {
    // Replace with a real log key from Firebase
    String exampleLogId = "REPLACE_WITH_REAL_LOG_ID";

    Map<String, Object> updates = new HashMap<>();
    updates.put("doseCount", 3); // change dose count
    updates.put("breathRating", 5.0f); // change breath rating

    viewModel.updateInventory(uid, exampleLogId, updates);
    // ViewModel will call loadLogByUser(uid) again internally
  }

  /**
   * Example: how to call deleteInventory on the ViewModel.
   */
  private void exampleDeleteLog() {
    // Replace with a real log key from Firebase
    String exampleLogId = "REPLACE_WITH_REAL_LOG_ID";

    viewModel.deleteInventory(uid, exampleLogId);
    // Again, ViewModel will refresh the list
  }
}
